# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            On AI
tagline:          'How I Learned To Stop Worrying And Love Stochastic Gradient Descent'
description:      'A practical guide to deep learning: for Python hackers, data scientists, the chronically-impatient, and the AI researchers of the future.'
url:              https://github.com/nikcheerla/deeplearningschool
baseurl:          "/"

author:
  name:           'Nikhil Cheerla'
  url:            https://www.linkedin.com/in/nikhilcheerla/

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/nikcheerla/deeplearningschool

prose:
  rooturl:        '_posts'
  siteurl:        http://nikcheerla.github.io/deeplearningschool
  media:          'media'
