# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            aischool
tagline:          'Stop Worrying And Love Stochastic Gradient Descent'
description:      'A practical guide to deep learning: for Python hackers, data scientists, the chronically-impatient, people who hate math but love computer science, and, most importantly, the AI researchers of the future.'
url:              https://github.com/nikcheerla/deeplearningschool
baseurl:          /

author:
  name:           'Nikhil Cheerla'
  url:            https://www.linkedin.com/in/nikhilcheerla/

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/nikcheerla/deeplearningschool
